language: python

python: "2.7"

install:
 - pip install pytest pytest-cov coveralls
 - pip install git+https://github.com/ladybug-tools/ladybug.git@master
 - sudo apt-get install radiance

script:
  - py.test --cov=. tests/

after_success:
  - coverage report
  - coveralls
